version: '3.8'
services:
  db:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user1'
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  api:
    container_name: api
    hostname: api
    build:
      context: ./api
      args:
        WORKDIR: $WORKDIR
    volumes:
      - ./api:/$WORKDIR
      - bundle_data:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

  front:
    container_name: front
    hostname: front
    build:
      context: ./front
      args:
        WORKDIR: $WORKDIR
    volumes:
      - ./front:/$WORKDIR
    ports:
      - 8000:8000
    depends_on:
      - api
    command: 'yarn dev'

volumes:
  bundle_data:
  postgres:
